### ISSUE TITLE
[Suggestion] A new name for the mod

### ISSUE THREAD

**Issue by RaptaG** [TopchetoEU/smooth-chunks#5]
Since this mod is different from the original, it should have a unique name, so that it can be recognized better.
Referring to #2 as well.

**Comment by TopchetoEU** [comment]
I'll certainly think of a new name, just don't have a good enough name yet. Suggestions for a name are greatly appreciated :)

**Comment by RaptaG** [comment]
Maybe, Chunk Animations?

**Comment by TopchetoEU** [comment]
Seems good, changing it to that one!
